version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./vhost.d:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./certs:/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

  landing:
    image: registry.digitalocean.com/dare2defi/metalancer-landing:latest
    environment:
      - VIRTUAL_HOST=metalancer.network
      - LETSENCRYPT_HOST=metalancer.network
      - LETSENCRYPT_EMAIL=defi2dare@gmail.com
      - VIRTUAL_PORT=8080
    expose:
        - 8080

volumes:
    certs:
    html:
    vhost: